version: '3.8'

services:
  nestjs-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    container_name: nestjs-dev
    ports:
      - '3000:3000'
    volumes:
      # Mount source code for hot reload
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
